### ISSUE TITLE
Update Readme/Documentation

### ISSUE THREAD

**Issue by Raporaz03** [Sirajmolla/Hacktoberfest-2022#37]
I will update your documentation by adding following things

1. Instructions for beginners.
2. Adding attractive images and gifs 
3. Information about project. What to do /things needed

Can I start?

**Comment by Sirajmolla** [comment]
Don't change Readme.md file you  can upload guide document

**Comment by Raporaz03** [comment]
but it is not visible on front page. Just txt file i can add it. ok ?

**Comment by techhunter2** [comment]
Hello Please assign me this issue. I'll add the amazing readme file which will contain a proper images and YouTube Videos link.
